#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Enable QM35 UWB module
CONFIG_QM35_UWB_ALIRO_ZEPHYR=y
#CONFIG_QM35_UWB_LIB=y
CONFIG_QOSAL_MAX_MUTEX=8

# Enable BLE Transport Protocol
CONFIG_DOOR_LOCK_BLE_UWB=y

# Enable power management for the device
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
