/*
 * Copyright (c) 2024 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-4-Clause
 */

#pragma once

#include "aliro/errors.h"
#include "aliro/types.h"

#include <cstddef>

namespace Aliro {

class CryptoImpl;

/**
 * Interface class for Crypto component.
 */
class Crypto {
public:
	/**
	 * @brief Initialize a crypto backend.
	 *
	 * @return ALIRO_NO_ERROR on success, ALIRO_ERROR_INTERNAL otherwise.
	 */
	AliroError Init();

	/**
	 * @brief Generate random bytes.
	 *
	 * @param rngBuf Output buffer for storing the generated bytes.
	 * @param rngBufLength Input number of bytes to generate.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError GenerateRandom(uint8_t *rngBuf, size_t rngBufLength);

	/**
	 * @brief Generate ephemeral EC key pair.
	 *
	 * @param keyId Output identifier for newly created keys.
	 * @param ephemeralPubKey Output buffer where the public key is to be copied.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError GenerateEphemeralKeyPair(CryptoTypes::KeyId &keyId, CryptoTypes::PublicKey &ephemeralPubKey);

	/**
	 * @brief Generate ephemeral EC key pair.
	 *
	 * @param keyId Output identifier for newly created keys.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError GenerateEphemeralKeyPair(CryptoTypes::KeyId &keyId);

	/**
	 * @brief Export EC public key.
	 *
	 * @param keyId input identifier of a private key for which the public key should be exported.
	 * @param ephemeralPubKey Output buffer where the public key is to be copied.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError ExportPublicKey(CryptoTypes::KeyId keyId, CryptoTypes::PublicKey &publicKey);

	/**
	 * @brief Export a key.
	 *
	 * @param keyId input identifier of a key to export.
	 * @param key output buffer where the key is to be copied.
	 * @param keyLength length of the key in bytes.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError ExportKey(CryptoTypes::KeyId keyId, uint8_t *key, size_t keyLength);

	/**
	 * Import a EC public key.
	 *
	 * @param key input buffer with public key.
	 * @param keyId output identifier of the imported key.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError ImportPublicKey(const CryptoTypes::PublicKey &key, CryptoTypes::KeyId &keyId);

	/**
	 * Import EC private key.
	 *
	 * @param key input buffer with private key.
	 * @param keyId output identifier of the imported private key.
	 * @param isPersistent flag indicating whether the key should be persistent or temporary.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError ImportPrivateKey(const CryptoTypes::PrivateKey &key, CryptoTypes::KeyId &keyId,
				    bool isPersistent = false);

	/**
	 * Preserve a volatile key by moving it to persistent slot.
	 *
	 * @param volatileKeyId input identifier of the volatile key.
	 * @param persistentKeyId input identifier of the persistent key.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError PreserveKey(CryptoTypes::KeyId &volatileKeyId, CryptoTypes::KeyId persistentKeyId);

	/**
	 * Destroy an key by ID.
	 *
	 * @param keyId identifier of a key to delete.
	 * NOTE: The function may set a ID to value 0.
	 *
	 * @param keyId an ID of the key to destroy.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError DestroyKey(CryptoTypes::KeyId &keyId);

	/**
	 * Generate signature for a message.
	 * NOTE: The Reader's private key (LTK) is used for message signing.
	 * The key must be loaded and avialable before this method is invoked.
	 *
	 * @param keyId input identifier of the private key to use for signing.
	 * @param msg input message to sign.
	 * @param msgLength input size of the message.
	 * @param signature output buffer where te signature is to be copied.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError GenerateSignature(CryptoTypes::KeyId privKeyId, const uint8_t *msg, const size_t msgLength,
				     CryptoTypes::Signature &signature);

	/**
	 * Verify signature of a message.
	 * NOTE: The Reader's public key (LTK) is used message verify.
	 * The key must be loaded and avialable before this method is invoked.
	 *
	 * @param pubKeyId input identifier of the public key to use for verification.
	 * @param msg input message whose signature is to be verified.
	 * @param msgLength input size of the message.
	 * @param signature input signature to verify.
	 *
	 * @return ALIRO_NO_ERROR when siganture is valid, ALIRO_INVALID_SIGNATURE otherwise.
	 */
	AliroError VerifySignature(CryptoTypes::KeyId pubKeyId, const uint8_t *msg, const size_t msgLength,
				   const CryptoTypes::Signature &signature);

	/**
	 * Comupte shared key with ECDH procedure.
	 * Aliro spec chapter 8.3.1.4.
	 * The function agrees common key using the ECDH procedure and derives shared key.
	 *
	 * @param privKeyId input identifier of private key id to use in procedure.
	 * @param publicKey input user device public key to use in procedure.
	 * @param transacionId input Transaction identifier.
	 * @param keyDhId output identifier of the agreed key.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError ComputeSharedKeyDH(CryptoTypes::KeyId privKeyId, const CryptoTypes::PublicKey &publicKey,
				      const CryptoTypes::TransactionIdentifier &transactionId,
				      CryptoTypes::KeyId &keyDhId);

	/**
	 * Derive session keys using Kdh.
	 * Aliro spec chapter 8.3.1.11.
	 * This function generates 160 bytes of derived key material and extracts from it symmetric keys:
	 * - ExpeditedSKReader
	 * - ExpeditedSKDevice
	 * - StepUpSK
	 * - BleSK
	 * - URSK
	 *
	 * @param kDh input identifier of the secret key.
	 * @param info input information for key derivation.
	 * @param infoLength input size of the info buffer.
	 * @param salt input a salt for key derivation.
	 * @param saltLength input size of the salt buffer.
	 * @param sessionVolatileKeys output bunch of session-bound keys.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError DeriveSessionKeys(CryptoTypes::KeyId kDh, const uint8_t *info, size_t infoLength,
				     const uint8_t *salt, size_t saltLength,
				     CryptoTypes::SessionBoundKeys &sessionVolatileKeys);

	/**
	 * Derive session keys using Kpersistent.
	 * Aliro spec chapter 8.3.1.10.
	 * This function generates 160 bytes of derived key material and extracts from it symmetric keys:
	 * - ExpeditedSKReader
	 * - ExpeditedSKDevice
	 * - StepUpSK
	 * - BleSK
	 * - URSK
	 *
	 * @param kpersistentKeyId input identifier of the secret key.
	 * @param info input information for key derivation.
	 * @param infoLength input size of the info buffer.
	 * @param salt input a salt for key derivation.
	 * @param saltLength input size of the salt buffer.
	 * @param sessionVolatileKeys output bunch of session-bound keys.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError DeriveSessionKeysFromKpersistent(CryptoTypes::KeyId kpersistentKeyId, const uint8_t *info,
						    size_t infoLength, const uint8_t *salt, size_t saltLength,
						    CryptoTypes::SessionBoundKeys &sessionVolatileKeys);

	/**
	 * Derive 32-bytes long BLE session key according to Aliro spec. v0.9.3 11.8.1
	 *
	 * @param inputKeyId input identifier of the secret key.
	 * @param info input information for key derivation.
	 * @param infoLength input size of the info buffer.
	 * @param salt input a salt for key derivation.
	 * @param saltLength input size of the salt buffer.
	 * @param outputKeyId output identifier of the derived key.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError DeriveBleSessionKey(CryptoTypes::KeyId inputKeyId, const uint8_t *info, size_t infoLength,
				       const uint8_t *salt, size_t saltLength, CryptoTypes::KeyId &outputKeyId);

	/**
	 * Derive persistent key.
	 *
	 * @param inputKeyId input identifier of the secret key.
	 * @param info input information for key derivation.
	 * @param infoLength input size of the info buffer.
	 * @param salt input a salt for key derivation.
	 * @param saltLength input size of the salt buffer.
	 * @param outputKeyId output persistent key.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError DeriveKpersistent(CryptoTypes::KeyId inputKeyId, const uint8_t *info, size_t infoLength,
				     const uint8_t *salt, size_t saltLength, CryptoTypes::KeyId &outputKeyId);

	/**
	 * Encrypt data payload.
	 *
	 * @param keyId input identifier of the key to use for encryption.
	 * @param plainTxt input raw paylod to encrypt.
	 * @param plainTxtLength input size of the payload.
	 * @param additionalData input a addtional data.
	 * @param additionalDataLength input a size of the addtional data.
	 * @param nonce input a nonce to use for operation.
	 * @param cipherText output encrypted paylod.
	 * @param authTag output authentication tag.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError EncryptPayload(CryptoTypes::KeyId keyId, const uint8_t *plainTxt, size_t plainTxtLength,
				  const uint8_t *info, size_t infoLength, const CryptoTypes::Nonce &nonce,
				  uint8_t *cipherText, CryptoTypes::AuthenticationTag &authTag);

	/**
	 * Encrypt data payload.
	 *
	 * @param keyId input identifier of the key to use for encryption.
	 * @param plainTxt input raw paylod to encrypt.
	 * @param plainTxtLength input size of the payload.
	 * @param cipherText output encrypted paylod.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError EncryptPayload(CryptoTypes::KeyId keyId, const uint8_t *plainTxt, size_t plainTxtLength,
				  uint8_t *cipherText);

	/**
	 * Authenticated decryption (AEAD) data payload.
	 *
	 * @param keyId input identifier of the key to use for decryption.
	 * @param cipherTextWithTag input encrypted and authenticated data. The buffer must contains the encrypted data
	 * followed by authentication tag.
	 * @param cipherTextWithTagLength input size of the cipherText buffer.
	 * @param additionalData input a addtional data that has been authenticated but not encrypted.
	 * @param additionalDataLength input a size of the addtional data.
	 * @param nonce input a nonce to use for operation with fixed size.
	 * @param plainText output buffer for decrypted data.
	 * @param plainTextLengt input/output size of the plainText buffer. On success the size of the output after
	 * decryprion.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError DecryptPayload(CryptoTypes::KeyId keyId, const uint8_t *cipherTextWithTag,
				  size_t cipherTextWithTagLength, const uint8_t *additionalData,
				  size_t additionalDataLength, const CryptoTypes::Nonce &nonce, uint8_t *plainText,
				  size_t &plainTextLength);

	/**
	 * Authenticated decryption (AEAD) data payload.
	 *
	 * @param keyId input identifier of the key to use for decryption.
	 * @param cipherText input encrypted and authenticated data. The buffer must contains the encrypted data
	 * followed by authentication tag.
	 * @param cipherTextLength input size of the cipherText buffer.
	 * @param nonce input a nonce to use for operation with fixed size.
	 * @param plainText output buffer for decrypted data
	 * @param plainTextLengt input/output size of the plainText buffer. On success the size of the output after
	 * decryprion.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError DecryptPayload(CryptoTypes::KeyId keyId, const uint8_t *cipherText, size_t cipherTextLength,
				  const CryptoTypes::Nonce &nonce, uint8_t *plainText, size_t &plainTextLength)
	{
		return DecryptPayload(keyId, cipherText, cipherTextLength, nullptr, 0U, nonce, plainText,
				      plainTextLength);
	}

	/**
	 * @brief Provisions a symmetric key for cryptographic operations.
	 *
	 * This function stores a symmetric key in a secure location for future use.
	 *
	 * @param key pointer to the symmetric key data.
	 * @param keyLength length of the symmetric key in bytes.
	 * @param keyId identifier for the key to be provisioned. This ID is used
	 *                   to reference the key in subsequent operations.
	 * @param isPersistent flag indicating whether the key should be persistent or temporary.
	 *
	 * @return ALIRO_NO_ERROR on success, error status otherwise.
	 */
	AliroError ProvisionSymmetricKey(const uint8_t *key, size_t keyLength, CryptoTypes::KeyId &keyId,
					 bool isPersistent = false);

	/**
	 * @brief Checks if a key ID exists (key is provisioned).
	 *
	 * @param keyId The key ID to check.
	 *
	 * @return ALIRO_NO_ERROR if the key available, a error code otherwise.
	 */
	AliroError IsKeyValid(CryptoTypes::KeyId keyId);

protected:
	Crypto() = default;
	Crypto(const Crypto &) = delete;
	Crypto(Crypto &&) = delete;
	~Crypto() = default;
	Crypto &operator=(const Crypto &) = delete;
	Crypto &operator=(Crypto &&) = delete;

private:
	bool mInitialized{ false };
	CryptoImpl *Impl();
};

extern Crypto &CryptoInstance();

} // namespace Aliro

#include "crypto_impl.h"
