sonar.projectKey=nrfconnect_ncs-door-lock-and-access-control
sonar.organization=nrfconnect
sonar.issue.ignore.multicriteria=disable_s6004,disable_s5945,disable_s5421,disable_s5008
# Disable: "if" and "switch" initializer should be used to reduce scope of variables
sonar.issue.ignore.multicriteria.disable_s6004.ruleKey=cpp:S6004
sonar.issue.ignore.multicriteria.disable_s6004.resourceKey=**
# Disable: C-style array should not be used
sonar.issue.ignore.multicriteria.disable_s5945.ruleKey=cpp:S5945
sonar.issue.ignore.multicriteria.disable_s5945.resourceKey=**
# Disable: Non-const global variables should not be used
sonar.issue.ignore.multicriteria.disable_s5421.ruleKey=cpp:S5421
sonar.issue.ignore.multicriteria.disable_s5421.resourceKey=**
# Disable: "void *" should not be used in typedefs, member variables, function parameters or return type cpp
sonar.issue.ignore.multicriteria.disable_s5008.ruleKey=cpp:S5008
sonar.issue.ignore.multicriteria.disable_s5008.resourceKey=**
sonar.exclusions=\
    **/*.py,\
    drivers/nfc/**,\
    **/zap-generated/**
sonar.coverage.exclusions=**
sonar.cpd.exclusions=\
    **/zcl_callbacks.cpp,\
    **/app_task.*,\
    **/init.*,\
    **/bolt_lock_manager.*,\
    subsys/aliro/uwb/**/*.h,\
    subsys/aliro/uwb/**/*.cpp,\
    tests/**
