# Copyright (c) 2025 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v3.3.0
      import: true
    - name: qm35-aliro-sdk
      url: https://gitlab.com/qorvo_sdk/public/devkits/qm35-aliro-sdk
      revision: v1.1.0
      groups:
        - qm35-aliro-sdk
    - name: ncs-door-lock-app-extensions
      remote: ncs
      repo-path: ncs-door-lock-app-extensions
      revision: v1.1.0
      groups:
        - ncs-door-lock-app-extensions
  group-filter:
    - -qm35-aliro-sdk
    - -ncs-door-lock-app-extensions
