# Copyright (c) 2025 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: nrfconnect-uwb-qorvo
      url-base: git@gitlab.com:qorvo/qswg/public
  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v3.2.0
      import: true
    - name: nrfconnect-sdk-qorvo
      remote: nrfconnect-uwb-qorvo
      repo-path: nrfconnect-sdk-qorvo
      revision: QM35ALIRO_ENG-0.5.0
      groups:
        - nrfconnect-sdk-qorvo
  group-filter:
    - -nrfconnect-sdk-qorvo
