#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

#
# Aliro
#

# Enable Aliro
CONFIG_NCS_ALIRO=y

# Basic system configuration
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_ASSERT=y
CONFIG_MPU_STACK_GUARD=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y

# Stack sizes
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# Logging
CONFIG_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_NCS_ALIRO_RFAL_LOG_LEVEL_DBG=y
CONFIG_USE_SEGGER_RTT=n
CONFIG_LOG_BACKEND_RTT=n
CONFIG_LOG_BACKEND_SHOW_COLOR=n
CONFIG_NCS_DOOR_LOCK_APP_LOG_LEVEL_INF=y

# Disable unused shell features
CONFIG_SHELL_VT100_COLORS=n
CONFIG_SHELL_HISTORY=n
CONFIG_SHELL_WILDCARD=n

# Set shell configuration
CONFIG_SHELL_MINIMAL=n
CONFIG_SHELL_DEVICE_HELPERS=y

# Increase shell buffer sizes
CONFIG_SHELL_BACKEND_SERIAL_RX_RING_BUFFER_SIZE=2048
CONFIG_SHELL_BACKEND_SERIAL_TX_RING_BUFFER_SIZE=1024

# Adjust logs queue size
CONFIG_SHELL_BACKEND_SERIAL_LOG_MESSAGE_QUEUE_SIZE=2048

# RFAL worker stack size (TODO: optimize)
CONFIG_RFAL_WORKER_THREAD_STACK_SIZE=8192

CONFIG_ACCESS_DECISION_INDICATOR=y

# Workaournd for Murata issue:
# https://github.com/csa-access-control/aliro-actuator/issues/114
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n


#
# Matter
#

# 3003
CONFIG_CHIP_DEVICE_DISCRIMINATOR=0xBBB
CONFIG_CHIP_DEVICE_SPAKE2_PASSCODE=30033003

# 32774 == 0x8006 (example lock-app)
CONFIG_CHIP_DEVICE_PRODUCT_ID=32774

# Suspend devices when the CPU goes into sleep
CONFIG_PM_DEVICE=y

# Try to disable unused RAM blocks to reduce power consumption
CONFIG_RAM_POWER_DOWN_LIBRARY=y

# Reduce application size
CONFIG_MATTER_LOG_LEVEL_INF=y
CONFIG_CHIP_APP_LOG_LEVEL=3

CONFIG_LOCK_MAX_CREDENTIAL_LENGTH=65
