#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Basic system configuration
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_NCS_SAMPLES_DEFAULTS=y
CONFIG_RESET_ON_FATAL_ERROR=n

# Aliro stack
CONFIG_NCS_ALIRO=y

# Logging
CONFIG_CONSOLE=y
CONFIG_LOG=y
CONFIG_NCS_ALIRO_LOG_LEVEL_DBG=y
CONFIG_NCS_ALIRO_RFAL_LOG_LEVEL_DBG=y

# Use test data for development purposes.
CONFIG_ALIRO_TEST_KEYS=y
CONFIG_NCS_ALIRO_FIXED_READER_GROUP_ID=y

# Use custom NFC driver
CONFIG_ALIRO_ISODEP_BACKEND_CUSTOM=y
CONFIG_ALIRO_NFC_DRIVER_CUSTOM=y

# Crypto
CONFIG_MBEDTLS_HEAP_SIZE=1024
