#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

#
# Aliro
#

CONFIG_NCS_ALIRO=y

CONFIG_NCS_ALIRO_RELEASE=y

CONFIG_DOOR_LOCK_RELEASE=y

# Basic system configuration
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBCPP=y

# Stack sizes
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=3072

#logging
CONFIG_LOG=n
CONFIG_USE_SEGGER_RTT=n

# Workaround for Murata issue:
# https://github.com/aliro-access-control/aliro-actuator/issues/114
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n

# Override default values to match Aliro requirements for APDU message sizes.
CONFIG_BT_BUF_ACL_RX_SIZE=271
CONFIG_BT_BUF_ACL_TX_SIZE=271
CONFIG_BT_L2CAP_TX_MTU=267

#
# Matter
#

# 3003
CONFIG_CHIP_DEVICE_DISCRIMINATOR=0xBBB
CONFIG_CHIP_DEVICE_SPAKE2_PASSCODE=30033003

# 32774 == 0x8006 (example lock-app)
CONFIG_CHIP_DEVICE_PRODUCT_ID=32774

# Suspend devices when the CPU goes into sleep
CONFIG_PM_DEVICE=y

# Try to disable unused RAM blocks to reduce power consumption
CONFIG_RAM_POWER_DOWN_LIBRARY=y

CONFIG_DOOR_LOCK_MATTER_ACCESS_MAX_CREDENTIAL_LENGTH=65

CONFIG_ASSERT=n
CONFIG_ASSERT_VERBOSE=n
CONFIG_ASSERT_NO_FILE_INFO=y

CONFIG_RESET_ON_FATAL_ERROR=y

CONFIG_UART_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_SHELL=n
CONFIG_NCS_SAMPLE_MATTER_TEST_SHELL=n
CONFIG_LOG_MODE_MINIMAL=n
CONFIG_SHELL_STACK_SIZE=4096

CONFIG_THREAD_NAME=n
CONFIG_BOOT_BANNER=n
CONFIG_PRINTK=n
CONFIG_PRINTK_SYNC=n
CONFIG_CHIP_LIB_SHELL=n
CONFIG_OPENTHREAD_SHELL=n
