#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# This file contains selected Kconfig options for the application.

# state machine framework
CONFIG_SMF=y

# compiler
CONFIG_DEBUG_OPTIMIZATIONS=y

# logging
CONFIG_LOG=y
CONFIG_NCS_NFC_READER_SAMPLE_LOG_LEVEL_INF=y

# use NFC STM driver HAL
CONFIG_NFC_DRIVER_STM=y
