#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_DOOR_LOCK_BLE_NUS=y

CONFIG_BT_NUS=y
CONFIG_BT_NUS_AUTHEN=y

CONFIG_BT_RX_STACK_SIZE=2048
CONFIG_BT_DEVICE_APPEARANCE=883

CONFIG_BT_FIXED_PASSKEY=y
