#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Enable QM35 UWB module library
CONFIG_QM35_UWB_LIB=y

# Disable NFC transport
CONFIG_DISABLE_ALIRO_NFC_TP=y
