#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# This file contains selected Kconfig options for the application.

# Disable Aliro stack for this sample
CONFIG_NCS_ALIRO=n

# compiler
CONFIG_DEBUG_OPTIMIZATIONS=y

# logging
CONFIG_LOG=y
CONFIG_NCS_NFC_READER_SAMPLE_LOG_LEVEL_INF=y

# use NFC STM driver HAL
CONFIG_NFC_DRIVER_STM=y

# set RFAL configuration
CONFIG_RFAL_FEATURE_NFCA=y
CONFIG_RFAL_FEATURE_WAKEUP_MODE=y
CONFIG_RFAL_FEATURE_T4T=y
CONFIG_RFAL_FEATURE_ISO_DEP=y
CONFIG_RFAL_FEATURE_ISO_DEP_POLL=y

CONFIG_ASSERT=y
