#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

#
# Aliro
#

CONFIG_NCS_ALIRO=y
CONFIG_DOOR_LOCK_ALIRO_LOCK_SIM=y

# Basic system configuration
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_ASSERT=y
CONFIG_MPU_STACK_GUARD=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y
CONFIG_THREAD_NAME=y

# Stack sizes
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=3072
CONFIG_SHELL_STACK_SIZE=4096

# Logging
CONFIG_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_DOOR_LOCK_RFAL_LOG_LEVEL_DBG=y
CONFIG_DOOR_LOCK_ALIRO_UWB_LOG_LEVEL_INF=y
CONFIG_USE_SEGGER_RTT=n
CONFIG_LOG_BACKEND_RTT=n
CONFIG_LOG_BACKEND_SHOW_COLOR=n
CONFIG_DOOR_LOCK_APP_LOG_LEVEL_INF=y
CONFIG_BT_HCI_CORE_LOG_LEVEL_ERR=y
CONFIG_BT_HCI_DRIVER_LOG_LEVEL_ERR=y
CONFIG_MATTER_LOG_LEVEL_INF=y
CONFIG_CHIP_APP_LOG_LEVEL=3

# Disable unused shell features
CONFIG_SHELL_VT100_COLORS=n
CONFIG_SHELL_HISTORY=n
CONFIG_SHELL_WILDCARD=n

# Set shell configuration
CONFIG_SHELL_MINIMAL=n
CONFIG_SHELL_DEVICE_HELPERS=y

# Increase shell buffer sizes
CONFIG_SHELL_BACKEND_SERIAL_RX_RING_BUFFER_SIZE=2048
CONFIG_SHELL_BACKEND_SERIAL_TX_RING_BUFFER_SIZE=1024

# Adjust logs queue size
CONFIG_SHELL_BACKEND_SERIAL_LOG_MESSAGE_QUEUE_SIZE=2048

# Workaround for Murata issue:
# https://github.com/aliro-access-control/aliro-actuator/issues/114
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n

# Override default values to match Aliro requirements for APDU message sizes.
CONFIG_BT_BUF_ACL_RX_SIZE=271
CONFIG_BT_BUF_ACL_TX_SIZE=271
CONFIG_BT_L2CAP_TX_MTU=267

#
# Matter
#

# Enable CHIP
CONFIG_CHIP=y
CONFIG_CHIP_DEVICE_PRODUCT_NAME="Door Lock"

# Enable Matter extended announcement and increase duration to 1 hour.
CONFIG_CHIP_BLE_EXT_ADVERTISING=y
CONFIG_CHIP_BLE_ADVERTISING_DURATION=60

# Enable Factory Data feature
CONFIG_CHIP_FACTORY_DATA=y
CONFIG_CHIP_FACTORY_DATA_BUILD=y

# Enable DK library
CONFIG_DK_LIBRARY=y

# Increase BT RX stack size to prevent stack overflow during BLE pairing
# Note: This workaround will be resolved in ncs v3.2.0 release
CONFIG_BT_RX_STACK_SIZE=2048

# Increase the heap size to 16K as Aliro+Matter configuration requires more memory.
# It's visible when working with ecosystems.
CONFIG_CHIP_MALLOC_SYS_HEAP_SIZE=16384

# Disable all logs by default to save memory,
# except those explicitly enabled for Matter and Aliro related.
CONFIG_LOG_DEFAULT_LEVEL=0

CONFIG_CHIP_NFC_ONBOARDING_PAYLOAD=n
CONFIG_CHIP_QSPI_NOR_POWER_MANAGEMENT_SUPPORT=n

# Required for Time Synchronization cluster
CONFIG_CHIP_ENABLE_READ_CLIENT=y

# Enable Matter shell
CONFIG_CHIP_LIB_SHELL=y
CONFIG_NCS_SAMPLE_MATTER_TEST_SHELL=y

# Enable Matter Access module
CONFIG_DOOR_LOCK_MATTER_ACCESS=y
CONFIG_DOOR_LOCK_MATTER_ACCESS_CREDENTIAL_TYPES_PIN=y
CONFIG_DOOR_LOCK_MATTER_ACCESS_CREDENTIAL_TYPES_ALIRO=y
CONFIG_DOOR_LOCK_MATTER_ACCESS_MAX_CREDENTIAL_LENGTH=65

# Override default discriminator (3003) and passcode (30033003)
CONFIG_CHIP_DEVICE_DISCRIMINATOR=0xBBB
CONFIG_CHIP_DEVICE_SPAKE2_PASSCODE=30033003

# 32774 == 0x8006 (example lock-app)
CONFIG_CHIP_DEVICE_PRODUCT_ID=32774

# Suspend devices when the CPU goes into sleep
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y

# Try to disable unused RAM blocks to reduce power consumption
CONFIG_RAM_POWER_DOWN_LIBRARY=y

# Disable unused NVS storage partition.
CONFIG_PM_PARTITION_SIZE_NVS_STORAGE=0
