#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

#
# Aliro
#

CONFIG_NCS_ALIRO=y
CONFIG_DOOR_LOCK_ALIRO_LOCK_SIM=y

CONFIG_NCS_ALIRO_RELEASE=y

CONFIG_DOOR_LOCK_RELEASE=y

# Basic system configuration
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBCPP=y

# Stack sizes
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=3072

#logging
CONFIG_LOG=n
CONFIG_USE_SEGGER_RTT=n

# Workaround for Murata issue:
# https://github.com/aliro-access-control/aliro-actuator/issues/114
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n

# Override default values to match Aliro requirements for APDU message sizes.
CONFIG_BT_BUF_ACL_RX_SIZE=271
CONFIG_BT_BUF_ACL_TX_SIZE=271
CONFIG_BT_L2CAP_TX_MTU=267

#
# Matter
#

# Enable CHIP
CONFIG_CHIP=y
CONFIG_CHIP_DEVICE_PRODUCT_NAME="Door Lock"

# Enable Matter extended announcement and increase duration to 1 hour.
CONFIG_CHIP_BLE_EXT_ADVERTISING=y
CONFIG_CHIP_BLE_ADVERTISING_DURATION=60

# Enable Factory Data feature
CONFIG_CHIP_FACTORY_DATA=y
CONFIG_CHIP_FACTORY_DATA_BUILD=y

# Enable DK library
CONFIG_DK_LIBRARY=y

# Increase BT RX stack size to prevent stack overflow during BLE pairing
# Note: This workaround will be resolved in ncs v3.2.0 release
CONFIG_BT_RX_STACK_SIZE=2048

# Increase the heap size to 16K as Aliro+Matter configuration requires more memory.
# It's visible when working with ecosystems.
CONFIG_CHIP_MALLOC_SYS_HEAP_SIZE=16384

# Disable all logs by default to save memory,
# except those explicitly enabled for Matter and Aliro related.
CONFIG_LOG_DEFAULT_LEVEL=0

CONFIG_CHIP_NFC_ONBOARDING_PAYLOAD=n
CONFIG_CHIP_QSPI_NOR_POWER_MANAGEMENT_SUPPORT=n

# Required for Time Synchronization cluster
CONFIG_CHIP_ENABLE_READ_CLIENT=y

# Enable Matter Access module
CONFIG_DOOR_LOCK_MATTER_ACCESS=y
CONFIG_DOOR_LOCK_MATTER_ACCESS_CREDENTIAL_TYPES_PIN=y
CONFIG_DOOR_LOCK_MATTER_ACCESS_CREDENTIAL_TYPES_ALIRO=y
CONFIG_DOOR_LOCK_MATTER_ACCESS_MAX_CREDENTIAL_LENGTH=65

# Override default discriminator (3003) and passcode (30033003)
CONFIG_CHIP_DEVICE_DISCRIMINATOR=0xBBB
CONFIG_CHIP_DEVICE_SPAKE2_PASSCODE=30033003

# 32774 == 0x8006 (example lock-app)
CONFIG_CHIP_DEVICE_PRODUCT_ID=32774

# Suspend devices when the CPU goes into sleep
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y

# Try to disable unused RAM blocks to reduce power consumption
CONFIG_RAM_POWER_DOWN_LIBRARY=y

CONFIG_ASSERT=n
CONFIG_ASSERT_VERBOSE=n
CONFIG_ASSERT_NO_FILE_INFO=y

CONFIG_RESET_ON_FATAL_ERROR=y

CONFIG_UART_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_SHELL=n
CONFIG_NCS_SAMPLE_MATTER_TEST_SHELL=n
CONFIG_LOG_MODE_MINIMAL=n
CONFIG_SHELL_STACK_SIZE=4096

CONFIG_THREAD_NAME=n
CONFIG_BOOT_BANNER=n
CONFIG_PRINTK=n
CONFIG_PRINTK_SYNC=n
CONFIG_CHIP_LIB_SHELL=n
CONFIG_OPENTHREAD_SHELL=n

# Disable unused NVS storage partition.
CONFIG_PM_PARTITION_SIZE_NVS_STORAGE=0
